### ISSUE TITLE
Some useful hacks?

### ISSUE THREAD

**Issue by Ottermanns** [supersambo/papis-tui#2]
Absolutely great. Works very well. I have some questions about the config. Sorry if I overlooked this in the documentation:

1. Is it possible to define a "page-down/up key" in the config? Scrolling with just "scroll_down/up" is really annoying.

2. After marking an entry I would like the cursor to move down one entry. But "' ':mark_selected;scroll_down" doesn't seem to work.

3. When sorting the entries by year I would like to sort in descending order, but I can not figure out how to set this in the config-file. "sy: sort --reverse year" for example doesn't work.

**Comment by supersambo** [comment]
Thank you for the first message here and sorry for the late reply, somehow I didn't get a notice:

1. Yes, there is page_down/page_up (with underscores).
2. For this very special case, there is mark_down. This is just a hardcoded command, unfortunately there is no way to chain commands yet. But I agree that would be great. I will put it on my list, but honestly I haven't touched this project in a while! 
3. Yes, you can sort reverse by adding a '-' to the end of your key. For instance "year-". I know that this is rather counter intuitive. I had to put it at the end because of the way commands are parsed

**Comment by supersambo** [comment]
I am closing this for now. If there are further questions feel free to reopen!
